// Pass-through shim for Apple's libmetalirconverter.dylib as bundled with CrossOver's D3DMetal.
//
// ACE COMBAT 8's sky/cloud renderer has one compute shader (TraceTilesClassifyCS) that uses
// 64-bit floats because of a single literal: `WaveActiveSum(1) * 0.3`. Metal has no FP64, so the
// converter rejects the shader (error 19) and the game's sky and sun/sky lighting stay black.
//
// When D3DMetal hands that exact DXIL container to the converter, this shim substitutes a copy
// recompiled from the shader's own embedded source with `float(WaveActiveSum(1u)) * 0.3f`.
// Every other shader is passed through untouched.
//
// orig_ids.h and fixed_blob.h are generated by build.sh from your own installed game.
#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "fixed_blob.h"
#include "orig_ids.h"

struct IRObject;
typedef IRObject* (*create_fn)(const char*, unsigned long);

static void shim_log(const char* msg) {
    const char* home = getenv("HOME");
    if (!home) return;
    char path[1024];
    snprintf(path, sizeof(path), "%s/Library/Logs/ac8-d3dmetal-shim.log", home);
    FILE* f = fopen(path, "a");
    if (!f) return;
    time_t t = time(nullptr);
    char ts[32];
    strftime(ts, sizeof(ts), "%Y-%m-%d %H:%M:%S", localtime(&t));
    fprintf(f, "%s [pid %d] %s\n", ts, (int)getpid(), msg);
    fclose(f);
}

// The real converter sits next to this dylib as libmetalirconverter_real.dylib.
static create_fn real_create() {
    static create_fn fn = nullptr;
    if (fn) return fn;
    Dl_info info;
    if (dladdr((void*)&shim_log, &info) && info.dli_fname) {
        char path[2048];
        strncpy(path, info.dli_fname, sizeof(path) - 1);
        path[sizeof(path) - 1] = 0;
        if (char* slash = strrchr(path, '/')) {
            size_t room = sizeof(path) - (size_t)(slash + 1 - path);
            snprintf(slash + 1, room, "libmetalirconverter_real.dylib");
            if (void* h = dlopen(path, RTLD_NOW | RTLD_LOCAL))
                fn = (create_fn)dlsym(h, "_Z22IRObjectCreateFromDXILPKcm");
        }
    }
    if (!fn) {
        shim_log("FATAL: could not resolve the real IRObjectCreateFromDXIL");
        abort();
    }
    return fn;
}

static bool is_target(const unsigned char* b, unsigned long size) {
    if (size < 32 || memcmp(b, "DXBC", 4) != 0) return false;
    if (size == kOrigSize && memcmp(b + 4, kOrigDigest, 16) == 0) return true;
    // Same shader repackaged (for example with debug parts stripped): match its HASH part.
    uint32_t total, nparts;
    memcpy(&total, b + 24, 4);
    memcpy(&nparts, b + 28, 4);
    if (total > size || nparts > 64 || 32 + 4ul * nparts > size) return false;
    for (uint32_t k = 0; k < nparts; k++) {
        uint32_t o;
        memcpy(&o, b + 32 + 4 * k, 4);
        if (o + 28ul > size) return false;
        if (memcmp(b + o, "HASH", 4) == 0 && memcmp(b + o + 12, kOrigHash, 16) == 0) return true;
    }
    return false;
}

// Same C++ signature (and therefore mangled name) as the converter's own entry point.
__attribute__((visibility("default")))
IRObject* IRObjectCreateFromDXIL(const char* bytes, unsigned long size) {
    create_fn real = real_create();
    if (bytes && is_target((const unsigned char*)bytes, size)) {
        shim_log("substituted TraceTilesClassifyCS (FP64 -> float)");
        return real((const char*)kFixedShader, kFixedShaderLen);
    }
    return real(bytes, size);
}
